<?php
// Auto-generated by Sam Anti Spam Setup. Edit credentials here if needed.
return array (
  'db' => 
  array (
    'host' => '127.0.0.1',
    'db_name' => 'sam_anti_spam_db',
    'user' => 'root',
    'pass' => '',
    'charset' => 'utf8mb4',
  ),
);
